server.port: 8080
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: opex-captcha
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
app:
  captcha-window-seconds: 600
