server.port: 8091
spring:
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: 127.0.0.1
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5436/opex_wallet
    username: ${dbusername}
    password: ${dbpassword}
    initialization-mode: always