server.port: 8091
spring:
  application:
    name: opex-wallet
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  redis:
    host: ${REDIS_HOST}
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_wallet
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

app:
  cors:
    allowed-hosts: https://opex.dev, http://localhost:3000
    allowed-patterns: http://192.168.*