server.port: 8091
spring:
  application:
    name: opex-wallet
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  redis:
    host: ${REDIS_HOST}
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_wallet
    username: ${dbusername}
    password: ${dbpassword}
    initialization-mode: always
  cloud:
    vault:
      host: ${VAULT_HOST}
    consul:
      host: ${CONSUL_HOST}
      port: 8500
