server.port: 8095
spring:
  application:
    name: opex-bc-gateway
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  redis:
    host: ${REDIS_HOST}
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_bc_gateway
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

app:
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs
  wallet:
    url: lb://wallet
