spring:
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  redis:
    host: ${REDIS_HOST}
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_accountant
    username: ${dbusername}
    password: ${dbpassword}
  cloud:
    vault:
      host: ${VAULT_HOST}
    consul:
      host: ${CONSUL_HOST}
  main:
    allow-bean-definition-overriding: true