server.port: 8089
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: opex-accountant
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  kafka:
    bootstrap-servers: 192.168.178.29:9092
    consumer:
      group-id: accountant
  redis:
    hostname: 127.0.0.1
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_accountant
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
app:
  coin: nln
  address: 1
  wallet:
    url: lb://opex-wallet/
