spring:
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  datasource:
    url: jdbc:postgresql://${DB_IP_PORT}/opex_auth
    username: opex
    password: hiopex
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

keycloak:
  migration:
    file: /opex-master-realm.json
  adminUrl: http://localhost:8083/auth
  frontendUrl: http://localhost:8083/auth

app:
  keycloak:
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
