server.port: 8083
spring:
  application:
    name: opex-auth
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/opex_auth
    username: opex
    password: hiopex
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: opex-admin
      password: hiopex
    realmImportFile: /opex-realm.json
  migration:
    action: import
    provider: singleFile
    file: classpath:/opex-master-realm.json
    strategy: OVERWRITE_EXISTING
  profile:
    feature:
      admin_fine_grained_authz: enabled
      token_exchange: enabled
