spring:
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  datasource:
    url: jdbc:postgresql://${DB_IP_PORT}/opex_auth
    username: ${dbusername}
    password: ${dbpassword}
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

keycloak:
  migration:
    file: /opex-master-realm.json
  adminUrl: https://demo.opex.dev:8443/auth
  frontendUrl: https://demo.opex.dev:8443/auth