version: '3.8'
services:
  postgres-opex:
    build: resources/postgres-image
  accountant:
    build: accountant/accountant-app
  eventlog:
    build: eventlog/eventlog-app
  matching-engine:
    build: matching-engine/matching-engine-app
  matching-gateway:
    build: matching-gateway/matching-gateway-app
  auth:
    build: user-management/keycloak-gateway
  wallet:
    build: wallet/wallet-app
  api:
    build: api/api-app
  websocket:
    build: websocket/websocket-app
  bc-gateway:
    build: bc-gateway/bc-gateway-app
  storage:
    build: storage/storage-app
  referral:
    build: referral/referral-app
  captcha:
    build: captcha/captcha-app
  admin:
    build: admin/admin-app
