version: '3.8'
services:
  kafka-1:
    environment:
      - KAFKA_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://kafka-1:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://kafka-1:9092
  kafka-2:
    environment:
      - KAFKA_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://kafka-2:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://kafka-2:9092
  kafka-3:
    environment:
      - KAFKA_LISTENERS=CLIENT://kafka-3:29092,EXTERNAL://kafka-3:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-3:29092,EXTERNAL://kafka-3:9092
  consul:
    ports:
      - "127.0.0.1:8500:8500"
      - "127.0.0.1:8300:8300"
      - "127.0.0.1:8600:8600"
  postgres-accountant:
    ports:
      - "127.0.0.1:5432:5432"
  postgres-eventlog:
    ports:
      - "127.0.0.1:5433:5432"
  postgres-auth:
    ports:
      - "127.0.0.1:5434:5432"
  postgres-wallet:
    ports:
      - "127.0.0.1:5435:5432"
  postgres-api:
    ports:
      - "127.0.0.1:5436:5432"
  postgres-bc-gateway:
    ports:
      - "127.0.0.1:5437:5432"