version: '3.8'
services:
  vault:
    build: docker-images/vault
  postgres-opex:
    build: docker-images/postgres
  accountant:
    build: accountant/accountant-app
    volumes:
      - "./preferences-$PREFERENCES_IDENTIFIER.yml:/preferences.yml"
  eventlog:
    build: eventlog/eventlog-app
  matching-engine:
    build: matching-engine/matching-engine-app
    volumes:
      - "./preferences-$PREFERENCES_IDENTIFIER.yml:/preferences.yml"
  matching-gateway:
    build: matching-gateway/matching-gateway-app
  auth:
    build: user-management/keycloak-gateway
  wallet:
    build: wallet/wallet-app
    volumes:
      - "./preferences-$PREFERENCES_IDENTIFIER.yml:/preferences.yml"
  api:
    build: api/api-app
    volumes:
      - "./preferences-$PREFERENCES_IDENTIFIER.yml:/preferences.yml"
  websocket:
    build: websocket/websocket-app
  bc-gateway:
    build: bc-gateway/bc-gateway-app
    volumes:
      - "./preferences-$PREFERENCES_IDENTIFIER.yml:/preferences.yml"
  storage:
    build: storage/storage-app
  referral:
    build: referral/referral-app
  captcha:
    build: captcha/captcha-app
  admin:
    build: admin/admin-app
