version: '3.8'
services:
  accountant:
    image: ghcr.io/opexdev/accountant:$TAG
    build: accountant/accountant-app
  eventlog:
    image: ghcr.io/opexdev/eventlog:$TAG
    build: eventlog/eventlog-app
  matching-engine:
    image: ghcr.io/opexdev/matching-engine:$TAG
    build: matching-engine/matching-engine-app
  matching-gateway:
    image: ghcr.io/opexdev/matching-gateway:$TAG
    build: matching-gateway/matching-gateway-app
  auth:
    image: ghcr.io/opexdev/auth:$TAG
    build: user-management/keycloak-gateway
  wallet:
    image: ghcr.io/opexdev/wallet:$TAG
    build: wallet/wallet-app
  market:
    image: ghcr.io/opexdev/market:$TAG
    build: market/market-app
  api:
    image: ghcr.io/opexdev/api:$TAG
    build: api/api-app
  bc-gateway:
    image: ghcr.io/opexdev/bc-gateway:$TAG
    build: bc-gateway/bc-gateway-app
