server.port: 8080

logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: storage
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true

app:
  root-dir: ${ROOT_DIR}
  cors:
    allowed-hosts: https://opex.dev, http://localhost:3000
    allowed-patterns: http://192.168.*
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs
