server:
  port: 8080
spring:
  application:
    name: opex-websocket
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT:localhost:9092}
    consumer:
      group-id: websocket
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT:localhost}/opex
    username: ${dbusername:opex}
    password: ${dbpassword:hiopex}
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    vault:
      host: ${VAULT_HOST}
      port: 8200
      scheme: http
      authentication: APPID
      app-id:
        user-id: co.nilin.opex.util.vault.VaultUserIdMechanism
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: ${spring.application.name}
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
  config:
    import: vault://secret/${spring.application.name}
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "prometheus", "metrics"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
app:
  address: 1
  auth:
    cert-url: http://auth:8080/auth/realms/opex/protocol/openid-connect/certs