server:
  port: 8097
spring:
  application:
    name: opex-websocket
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: 192.168.178.29:9092
    consumer:
      group-id: websocket
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_api
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
app:
  auth:
    cert-url: http://localhost:8083/auth/realms/opex/protocol/openid-connect/certs