spring:
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500
  main:
    allow-bean-definition-overriding: true

app:
  auth:
    keycloak:
      client-secret: ${KEYCLOAK_CLIENT_SECRET}