server:
  port: 8098
spring:
  application:
    name: opex-admin
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
app:
  keycloak:
    url: lb://opex-auth/auth
    realm: opex
    client-id: opex-admin
    client-secret: secret
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs