server:
  port: 8080
spring:
  application:
    name: opex-admin
  main:
    allow-bean-definition-overriding: true
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
app:
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs
    keycloak:
      url: http://auth:8080/auth
      realm: opex
      client-id: opex-admin
      client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}