server:
  port: 8080
spring:
  application:
    name: opex-market
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT:localhost:9092}
    consumer:
      group-id: market
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT:localhost}/opex
    username: ${dbusername:opex}
    password: ${dbpassword:hiopex}
    initialization-mode: always
  cache:
    type: redis
  redis:
    host: redis-cache
    port: 6379
  cloud:
    bootstrap:
      enabled: true
    vault:
      host: ${VAULT_HOST}
      port: 8200
      scheme: http
      authentication: APPID
      app-id:
        user-id: co.nilin.opex.market.app.utils.VaultUserIdMechanism
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: ${spring.application.name}
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
  config:
    import: vault://secret/${spring.application.name}
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
logbook:
  secure-filter:
    enabled: true
  format:
    style: http
  filter:
    enabled: true
    form-request-mode: BODY
  attribute-extractors:
    - type: JwtFirstMatchingClaimExtractor
      claim-names: [ "sub", "subject" ]
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
    json-body-fields:
      - password
    replacement: "***"
  write:
    max-body-size: 10_000 #kb
  predicate:
    exclude:
      - path: /auth**
      - path: /actuator/**
      - path: /swagger**
    include:
      - path: /v1/order/**
logging:
  level:
    co.nilin: INFO
app:
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs
swagger:
  authUrl: ${SWAGGER_AUTH_URL:https://api.opex.dev/auth}/realms/opex/protocol/openid-connect/token}
