server.port: 8090
spring:
  application:
    name: opex-eventlog
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: eventlog
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_eventlog
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    vault:
      host: ${VAULT_HOST}
      port: 8200
      scheme: http
      authentication: APPID
      app-id:
        user-id: co.nilin.opex.util.vault.VaultUserIdMechanism
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: ${spring.application.name}
  config:
    import: vault://secret/${spring.application.name}