version: '3.8'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    volumes:
      - $DATA/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    volumes:
      - $DATA/kafka-data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  consul:
    image: 'consul'
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - $DATA/redis-data:/var/lib/redis
      - $DATA/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  postgres-accountant:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_accountant
    volumes:
      - $DATA/accountant-data:/var/lib/postgresql/data/
    networks:
      - opex
  postgres-eventlog:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_eventlog
    volumes:
      - $DATA/runtime/eventlog-data:/var/lib/postgresql/data/
    networks:
      - opex
  postgres-auth:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_auth
    volumes:
      - $DATA/auth-data:/var/lib/postgresql/data/
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  postgres-wallet:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_wallet
    volumes:
      - $DATA/wallet-data:/var/lib/postgresql/data/
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  postgres-api:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_api
    volumes:
      - $DATA/api-data:/var/lib/postgresql/data/
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  postgres-bc-gateway:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_bc_gateway
    volumes:
      - $DATA/bc-gateway-data:/var/lib/postgresql/data/
    networks:
      - opex
    deploy:
      restart_policy:
        condition: on-failure
  accountant:
    build:
      context: ../accountant/accountant-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_ACTIVE=docker,demo,scheduled
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-accountant
    networks:
      opex:
        aliases:
          - accountant
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-accountant
  eventlog:
    build:
      context: ../eventlog/eventlog-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m
      - SPRING_PROFILES_ACTIVE=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-eventlog
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-eventlog
  matching-engine:
    build:
      context: ../matching-engine/matching-engine-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_ACTIVE=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
    depends_on:
      - zookeeper
      - kafka
      - redis
  matching-gateway:
    build:
      context: ../matching-gateway/matching-gateway-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
    depends_on:
      - zookeeper
      - kafka
      - consul
  auth:
    build:
      context: ../user-management/keycloak-gateway
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_ACTIVE=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-auth
      - PROXY_ADDRESS_FORWARDING=true
      - WORKING_DIR=$DATA
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-auth
    deploy:
      restart_policy:
        condition: on-failure
  wallet:
    build:
      context: ../wallet/wallet-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-wallet
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-wallet
    deploy:
      restart_policy:
        condition: on-failure
  api:
    build:
      context: ../api/api-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker,demo
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-api
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-api
    deploy:
      restart_policy:
        condition: on-failure
  websocket:
    build:
      context: ../websocket/websocket-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker
      - KAFKA_IP_PORT=kafka:9092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-api
    depends_on:
      - zookeeper
      - kafka
      - consul
      - postgres-api
    deploy:
      restart_policy:
        condition: on-failure
  bc-gateway:
    build:
      context: ../bc-gateway/bc-gateway-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker,demo,scheduled
      - KAFKA_IP_PORT=kafka:9092
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-bc-gateway
    depends_on:
      - zookeeper
      - kafka
      - redis
      - consul
      - postgres-bc-gateway
    deploy:
      restart_policy:
        condition: on-failure
  storage:
    build:
      context: ../storage/storage-app
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_DEFAULT=docker
      - CONSUL_HOST=consul
    depends_on:
      - consul
    deploy:
      restart_policy:
        condition: on-failure
  nginx:
    image: jboesl/docker-nginx-headers-more
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - $DATA/www:/data/www
    depends_on:
      - wallet
      - auth
      - matching-gateway
      - api
networks:
  opex:
    driver: bridge
