server.port: 8094
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: opex-api
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  kafka:
    bootstrap-servers: 192.168.178.29:9092
    consumer:
      group-id: api
  redis:
    host: 127.0.0.1
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_api
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    vault:
      host: ${VAULT_HOST}
      port: 8200
      scheme: http
      authentication: APPID
      app-id:
        user-id: co.nilin.opex.util.vault.VaultUserIdMechanism
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: ${spring.application.name}
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
  config:
    import: vault://secret/${spring.application.name}
app:
  accountant:
    url: lb://opex-accountant
  matching-gateway:
    url: lb://opex-gateway
  wallet:
    url: lb://opex-wallet
  opex-bc-gateway:
    url: lb://opex-bc-gateway
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs

swagger.authUrl: https://api.opex.dev