server.port: 8093
spring:
  application:
    name: opex-gateway
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
    consumer:
      group-id: gateway
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
