server.port: 8080
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: opex-matching-gateway
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT:localhost:9092}
    consumer:
      group-id: gateway
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "prometheus", "metrics"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
swagger.authUrl: ${SWAGGER_AUTH_URL:https://api.opex.dev/auth}/realms/opex/protocol/openid-connect/token
app:
  accountant:
    url: lb://opex-accountant
  auth:
    cert-url: lb://opex-auth/auth/realms/opex/protocol/openid-connect/certs
