server.port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: opex-config
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT:localhost:9092}
    consumer:
      group-id: wallet
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
app:
  auth:
    cert-url: http://auth:8080/auth/realms/opex/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    co.nilin: INFO
    reactor.netty.http.client: INFO
swagger.authUrl: ${SWAGGER_AUTH_URL:https://api.opex.dev/auth}/realms/opex/protocol/openid-connect/token
