server.port: 8095
spring:
  application:
    name: opex-bc-gateway
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: localhost:2181
    consumer:
      group-id: opex-bc-gateway
  redis:
    host: 127.0.0.1
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_bc_gateway
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
logging:
  level:
    org.apache.kafka: DEBUG

swagger.authUrl: https://api.opex.dev
