name: Deploy OPEX - Dev

on:
  push:
    branches:
      - dev

jobs:
  jenkinsJob:
    name: Build OPEX new dev version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger opex-build-job on jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "opex-core-dev-deploy"
