name: Push images on main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 17 ]
    name: Build OPEX and run tests with java ${{ matrix.java }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
#          cache: maven
      - name: Build
        run: mvn -B -T 1C clean install
      - name: Run Tests
        run: mvn -B -T 1C -Dskip.unit.tests=false surefire:test
      - name: Build Docker images
        env:
          TAG: latest
        run: docker compose -f docker-compose.build.yml build
      - name: Login to NiliN Container Registry
        run: docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }} registry.opex.dev
      - name: Push images to Registry
        env:
          TAG: latest
        run: docker compose -f docker-compose.build.yml push
